myexe: MyMain.o MyStrFunc.o MyMathFunc.o
	gcc -o myexe MyMain.o myStrFunc.o MyMathFunc.o 
MyMathFunc.o: MyMathFunc.c
	gcc -c MyMathFunc.c
MyStrFunc.o: myStrFunc.c
	gcc -c myStrFunc.c
MyMain.o: MyMain.c
	gcc -c MyMain.c

